nlw:
  [
    "Celniker, Susan",
    "Piano, Fabio",
    "Waterston, Robert",
    "Gingeras, Thomas" # => Celniker
  ]

MPerry:
  [
    "Ahringer, Julie", # => Lieb
    "Henikoff, Steven",
    "Karpen, Gary",
    "Lieb, Jason",
    "Snyder, Michael",
    "White, Kevin"
  ]

paul:
  [
    "Henikoff, Steven",
    "Piano, Fabio"
  ]

pruzanov:
  [
    "Lai, Eric",
    "MacAlpine, David"
  ]

yostinso:
  [
    "Stein, Lincoln" 
  ]


#nlw:
#  [ "Lewis, Suzi" ]
