loaded_ids_url: "http://intermine.modencode.org/query/service/template/results?name=getSubmissions&constraint1=Submission&op1=LOOKUP&value1=*&extra1=&format=tab"
link_template: "http://intermine.modencode.org/query/portal.do?class=Submission&externalid=%d"
cache_file: "tmp/modmine_loaded_ids.tsv"
