Celniker, Susan: Drosophila melanogaster
Henikoff, Steven:
Karpen, Gary: Drosophila melanogaster
Lai, Eric: Drosophila melanogaster
Lieb, Jason: Caenorhabditis elegans
MacAlpine, David: Drosophila melanogaster
Oliver, Brian: Drosophila melanogaster
Piano, Fabio: Caenorhabditis elegans
Snyder, Michael: Caenorhabditis elegans
Stein, Lincoln:
Waterston, Robert: Caenorhabditis elegans
White, Kevin: Drosophila melanogaster
