Celniker, Susan:
  [
  "Brenner, Steven",
  "Brent, Michael",
  "Cherbas, Peter",
  "Gingeras, Thomas",
  "Graveley, Brenton",
  "Hoskins, Roger",
  "Perrimon, Norbert",
  "Oliver, Brian"
  ]
Henikoff, Steven:
  [
  "Ahmad, Kamran"
  ]
Karpen, Gary:
  [
  "Elgin, Sarah",
  "Kuroda, Mitzi",
  "Park, Peter",
  "Pirrotta, Vincent"
  ]
Lai, Eric:
  [
  "Hannon, Gregory"
  ]
Lieb, Jason:
  [
  "Ahringer, Julie",
  "Dernburg, Abby",
  "Desai, Arshad",
  "Green, Roland",
  "Liu, Xiaole",
  "Segal, Eran",
  "Strome, Susan"
  ]
MacAlpine, David:
  [
  "Orr-Weaver, Terry"
  ]
Oliver, Brian:
  [
  "Oliver, Brian"
  ]
Piano, Fabio:
  [
  "Gunsalus, Kristin",
  "Kim, John",
  "Rajewsky, Nikolaus"
  ]
Snyder, Michael:
  [
  "Gerstein, Mark",
  "Hyman, Anthony",
  "Kim, Stuart",
  "Reinke, Valerie",
  "Waterston, Robert"
  ]
Stein, Lincoln:
  [
  "Lewis, Suzanna",
  "Kent, James",
  "Micklem, Gos"
  ]
Waterston, Robert:
  [
  "Gerstein, Mark",
  "Green, Philip",
  "MacCoss, Michael",
  "Miller, David",
  "Reinke, Valerie",
  "Slack, Frank"
  ]
White, Kevin:
  [
  "Bellen, Hugo",
  "Bulyk, Martha",
  "Collart, Frank",
  "Hoskins, Roger",
  "Kellis, Manolis",
  "Posakony, James",
  "Ren, Bing",
  "Russell, Steven",
  "White, Robert"
  ]
