# A list of the 
workers:
  ## Main
  - {
      name: modencode-www1,
      ip: 206.108.121.116,
      disallow_pis: { "Lai, Eric" },
      disallow_users: { "pruzanov" }
    }
  - {
      name: modencode-www2,
      ip: 206.108.121.113
    }
  - {
      name: modencode-www3,
      ip: 206.108.121.114
    }
  - {
      name: modencode-www4,
      ip: 206.108.121.115
    }

